# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{faker-medical}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tom & Russell"]
  s.date = %q{2011-08-14}
  s.description = %q{This gem is an extension of the Faker Gem to generate SSN, DEA, and NPI Numbers}
  s.email = %q{thing2@jackhq.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "faker-medical.gemspec",
    "lib/faker_dea.rb",
    "lib/faker_npi.rb",
    "lib/faker_patient.rb",
    "lib/faker_ssn.rb",
    "spec/lib/faker_dea_spec.rb",
    "spec/lib/faker_npi_spec.rb",
    "spec/lib/faker_patient_spec.rb",
    "spec/lib/faker_ssn_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "test/helper.rb",
    "test/test_faker-medical.rb",
    "version.yml"
  ]
  s.homepage = %q{http://github.com/jackhq/faker-medical}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Faker Extension for Medical Numbers}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<faker>, [">= 0"])
      s.add_runtime_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<faker>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<faker>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

